<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;
use Joomla\Database\DatabaseInterface;

#use NPEU\Plugin\Content\TopicReplies\Helper\TopicRepliesHelper;
use NPEU\Template\L2b\Site\Helper\L2BHelper as TplL2BHelper;

$comments_enabled = TplL2BHelper::has_comments_enabled();



/** @var \Joomla\Component\Content\Site\View\Article\HtmlView $this */
// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = $this->getCurrentUser();
$info    = $params->get('info_block_position', 0);
#$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h3';
$htag    = 'h2';


?>
<div class="l-box  l-box--space--edge  longform-content">
    <div class="c-discussion-board">
        <?php if ($comments_enabled) : ?>
        <article class="c-discussion-board__post  d-background--lightest  d-border-rounded  c-panel">
        <?php else: ?>
        <article class="">
        <?php endif; ?>
            <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">


            <?php if ($params->get('show_title')) : ?>
            <div<?php if ($comments_enabled) : ?> class="c-discussion-board__post-banner"<?php endif; ?>>
                <?php if ($comments_enabled) : ?>
                <div class="l-layout l-row  l-gutter--s  l-flush-edge-gutter">
                <div class="ff-width-100--30--20">
                <?php endif; ?>
                <?php // We don't need anything here yet but it's a better layout. Could be useful in the future though. ?>
                    <div class="c-discussion-board__header-info"></div>
                <?php if ($comments_enabled) : ?>
                    </div>
                    <div class="ff-width-100--30--80">
                <?php endif; ?>
                <<?php echo $htag; ?><?php if ($comments_enabled) : ?> class="c-discussion-board__post-title"<?php endif; ?>>
                    <?php echo $this->escape($this->item->title); ?>
                </<?php echo $htag; ?>>
                <?php if ($comments_enabled) : ?>
                </div>
                </div>
                <?php endif; ?>
            </div>
            <?php endif; ?>


            <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
            <?php echo $this->item->event->afterDisplayTitle; ?>

            <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
            <?php echo $this->item->event->beforeDisplayContent; ?>

            <?php if ($comments_enabled) : ?>
            <div class="l-layout l-row  l-gutter--s  l-flush-edge-gutter">
            <div class="c-discussion-board__post-info  ff-width-100--30--20">
            <?php endif; ?>

            <?php if ($canEdit && $comments_enabled) : ?>
                <?php #echo LayoutHelper::render('joomla.content.icons', ['params' => $params, 'item' => $this->item]); ?>
            <?php endif; ?>


            <?php echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'above']); ?>


            <?php if ($comments_enabled) : ?>
            </div>
            <div class="c-discussion-board__post-body  ff-width-100--30--80">
            <?php endif; ?>



            <?php /*<div class="com-content-article__body  c-panel  d-background--lightest  d-border--rounded">*/ ?>
            <div class="com-content-article__body">
                <?php echo $this->item->text; ?>
            </div>
            <?php if ($comments_enabled) : ?>
            </div>
            </div>
            <?php endif; ?>

            <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
            <?php echo $this->item->event->afterDisplayContent; ?>

        </article>
    </div>
</div>
<?php
if (!$comments_enabled) {
    $doc        = Factory::getDocument();
    $doc->article = $this->item;
}
?>